build-sys: look for function 'backtrace' also in library 'ubacktrace'
Using OpenEmbedded with 'minimal-uclibc' for 'MACHINE = "beagleboard"'
compilation fails with the following error [1].

        […]
          CCLD   pulseaudio
        ./.libs/libpulsecommon-0.9.22.so: undefined reference to `backtrace_symbols'
        ./.libs/libpulsecommon-0.9.22.so: undefined reference to `backtrace'
        collect2: ld returned 1 exit status
        make[3]: *** [pulseaudio] Error 1

Using uClibc 'backtrace' is in the library 'ubacktrace' and needs to be
searched in there. This patch is used successfully in OpenEmbedded[2].

[1] http://lists.linuxtogo.org/pipermail/openembedded-devel/2011-May/032979.html
[2] http://cgit.openembedded.org/cgit.cgi/openembedded/commit/?id=0086e0506eb4939150bb50ec337d7f6787b8ae8a